### ISSUE TITLE
Prevent SQL injection

### ISSUE THREAD

**Issue by eric-do** [May-Take-A-Second/ReviewsAPI#3]
https://github.com/May-Take-A-Second/ReviewsAPI/blob/f66e922cdc3da5ef3a3776896943ac5f8f3e44cd/server/models/reviews.js#L21

You should be using either `?` or `connection.escape()` to prevent malicious values being passed into your variables.

Please see npm mysql [docs](https://www.npmjs.com/package/mysql#escaping-query-values).

**Comment by willtrinh** [comment]
Thanks @eric-do for the suggestion. I went ahead and use `escape()` for all of my `INSERT` queries. You can refer to this commit `f1c9c4813e5bcb8e55f6b90548d795d1f50ba1ec` to see the changes.
